"""Cria tabela salas

Revision ID: 86d12f6af084
Revises: 
Create Date: 2025-07-14 14:11:39.470711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d12f6af084'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_locatario', sa.String(length=100), nullable=False),
    sa.Column('sala', sa.String(length=100), nullable=False),
    sa.Column('email_locatario', sa.String(length=120), nullable=False),
    sa.Column('telefone_locatario', sa.String(length=30), nullable=True),
    sa.Column('data_locacao', sa.DateTime(), nullable=True),
    sa.Column('observacao_responsavel_coop', sa.Text(), nullable=True),
    sa.Column('observacao_locatario', sa.Text(), nullable=True),
    sa.Column('assinatura', sa.String(length=255), nullable=True),
    sa.Column('equipamentos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('caminho_foto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formularios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    op.drop_table('salas')
    op.drop_table('formularios')
    op.drop_table('equipamentos')
    # ### end Alembic commands ###
